server:
  port: 9003
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: bidang-urusan-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/kertaskerja_bidang_urusan
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/kertaskerja_bidang_urusan
kertaskerja:
  status: BIDANG URUSAN SERVICE IS UP
  client:
    urusan-service-uri: http://localhost:9002
