apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidang-urusan-service
  labels:
    app: bidang-urusan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidang-urusan-service
  template:
    metadata:
      labels:
        app: bidang-urusan-service
    spec:
      containers:
        - name: bidang-urusan-service
          image: bidang-urusan-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://kertaskerja-postgres:5432/kertaskerja_bidang_urusan
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://kertaskerja-postgres:5432/kertaskerja_bidang_urusan
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
